### ISSUE TITLE
Please bother to provide clear instructions on how to download your end product.

### ISSUE THREAD

**Issue by jmcd040** [franklai/synologylyric#1]
The title says it all. Where is the file that I can download and install in Synology Audio Station?

**Comment by franklai** [comment]
you can check this web page (video) for installation guide

https://my-doodads.com/synology-nas-quick-tip-how-to-add-a-lyrics-plugin-to-audio-station/

**Comment by h00** [comment]
I am with jmc on this. That video is actually what lead me to your repo. The video suggests we should find some aum files at bitbucket, however that now returns a 404. It seems all things point to this repo at this point, however I am not seeing any .aum files here. I see some PHP and composer files, however I haven't done any real PHP dev work in years at this point. Perhaps your repo isn't intended to provide the actual plugins? Please update the readme so those that are not intimately familiar with composer and synology can understand the intent of your repo.

**Comment by franklai** [comment]
.aum files are under https://github.com/franklai/synologylyric/releases

**Comment by h00** [comment]
Thanks much Frank.
